name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    # v2にするとgh-pagesへのpushで落ちる
    - uses: actions/checkout@v1
      with:
        path: ${{ github.workspace }}/${{ github.repository }}
    #   path: ${{ github.repository }}

    - name: check tree
      run: ls -R

    # - name: checkout ACL
    #   uses: actions/checkout@v2
    #   with:
    #     repository: atcoder/ac-library
    #     path: ac-library

    # - name: Set up Python
    #   uses: actions/setup-python@v1
    # - name: Set up Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.8"

    # - name: Install dependencies
    #   run: pip3 install -U online-judge-verify-helper
      # run: pip install git+https://github.com/bayashi-cl/verification-helper@modify

    # - name: Run tests
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     GH_PAT: ${{ secrets.GH_PAT }}
      #   CPLUS_INCLUDE_PATH: ${{ github.workspace }}/ac-library
      # working-directory: ./${{ github.repository }}
      # run: oj-verify all
